export { default as Categories } from './Categories'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Layout } from './Layout'
export { default as Navbar } from './Navbar'
export { default as Showcase } from './Showcase'
export { default as Slider } from './Slider'
export { default as VehicleDetails } from './VehicleDetails'
